//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServiceReferenceProveedor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Proveedor))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProveedor.IProveedor")]
    public interface IProveedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/GetAll", ReplyAction="http://tempuri.org/IProveedor/GetAllResponse")]
        PL.ServiceReferenceProveedor.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/GetAll", ReplyAction="http://tempuri.org/IProveedor/GetAllResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/GetById", ReplyAction="http://tempuri.org/IProveedor/GetByIdResponse")]
        PL.ServiceReferenceProveedor.Result GetById(int IdProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/GetById", ReplyAction="http://tempuri.org/IProveedor/GetByIdResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> GetByIdAsync(int IdProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Add", ReplyAction="http://tempuri.org/IProveedor/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReferenceProveedor.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL.ServiceReferenceProveedor.Result Add(ML.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Add", ReplyAction="http://tempuri.org/IProveedor/AddResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> AddAsync(ML.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Update", ReplyAction="http://tempuri.org/IProveedor/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL.ServiceReferenceProveedor.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL.ServiceReferenceProveedor.Result Update(ML.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Update", ReplyAction="http://tempuri.org/IProveedor/UpdateResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> UpdateAsync(ML.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Delete", ReplyAction="http://tempuri.org/IProveedor/DeleteResponse")]
        PL.ServiceReferenceProveedor.Result Delete(int IdProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Delete", ReplyAction="http://tempuri.org/IProveedor/DeleteResponse")]
        System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> DeleteAsync(int IdProveedor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProveedorChannel : PL.ServiceReferenceProveedor.IProveedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProveedorClient : System.ServiceModel.ClientBase<PL.ServiceReferenceProveedor.IProveedor>, PL.ServiceReferenceProveedor.IProveedor {
        
        public ProveedorClient() {
        }
        
        public ProveedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProveedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL.ServiceReferenceProveedor.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public PL.ServiceReferenceProveedor.Result GetById(int IdProveedor) {
            return base.Channel.GetById(IdProveedor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> GetByIdAsync(int IdProveedor) {
            return base.Channel.GetByIdAsync(IdProveedor);
        }
        
        public PL.ServiceReferenceProveedor.Result Add(ML.Proveedor proveedor) {
            return base.Channel.Add(proveedor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> AddAsync(ML.Proveedor proveedor) {
            return base.Channel.AddAsync(proveedor);
        }
        
        public PL.ServiceReferenceProveedor.Result Update(ML.Proveedor proveedor) {
            return base.Channel.Update(proveedor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> UpdateAsync(ML.Proveedor proveedor) {
            return base.Channel.UpdateAsync(proveedor);
        }
        
        public PL.ServiceReferenceProveedor.Result Delete(int IdProveedor) {
            return base.Channel.Delete(IdProveedor);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReferenceProveedor.Result> DeleteAsync(int IdProveedor) {
            return base.Channel.DeleteAsync(IdProveedor);
        }
    }
}
