//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomovilProveedor
    {
        public int IdAutomovilProveedor { get; set; }
        public Nullable<int> IdAutomovil { get; set; }
        public Nullable<int> IdProveedor { get; set; }
    
        public virtual Automovil Automovil { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
