//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automovil
    {
        public Automovil()
        {
            this.AutomovilProveedors = new HashSet<AutomovilProveedor>();
        }
    
        public int IdAutomovil { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual ICollection<AutomovilProveedor> AutomovilProveedors { get; set; }
    }
}
